apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ default "bankapp-namespace" .Values.namespace }}
data:
  MONGO_INITDB_DATABASE: {{ .Values.configmap.data.MONGO_INITDB_DATABASE }}
  QUARKUS_MONGODB_DATABASE: {{ .Values.configmap.data.MONGO_INITDB_DATABASE }}
  QUARKUS_MONGODB_CONNECTION_STRING: mongodb://{{ .Values.db_statefulset.name }}-0.{{ .Values.db_statefulset.name }}-headless.{{ default "bankapp-namespace" .Values.namespace }}.svc.cluster.local:27017
