apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_deployment.name }}
  namespace: {{ default "bankapp-namespace" .Values.namespace }}
  labels:
    app: {{ .Values.app_deployment.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app_deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_deployment.name }}
    spec:
      initContainers:
      - name: "wait-for-{{ .Values.db_statefulset.name }}"
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z {{ .Values.db_statefulset.name }}-0.{{ .Values.db_statefulset.name }}-headless 27017; do echo waiting for mongodb; sleep 5; done;']
      containers:
      - name: {{ .Values.app_deployment.name }}
        image: {{ .Values.image.app }}
        ports:
        - containerPort: 8080
        env:
        - name: QUARKUS_MONGODB_CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configmap.name }}
              key: QUARKUS_MONGODB_CONNECTION_STRING
        - name: QUARKUS_MONGODB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configmap.name }}
              key: QUARKUS_MONGODB_DATABASE
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: {{ .Values.app_deployment.mem_req}}
            cpu: {{ .Values.app_deployment.cpu_req}}
          limits:
            memory: {{ .Values.app_deployment.mem_limit}}
            cpu: {{ .Values.app_deployment.cpu_limit}}
