version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=Test@123
      - POSTGRES_DB=BankDB
    volumes:
      - bankapp-volume:/var/lib/postgresql/data
    networks:
      - bankapp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  mainapp:
    image: ${DUSER}/${IMAGE}
    container_name: Bankapp
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/BankDB
      - SPRING_DATASOURCE_PASSWORD=Test@123
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bankapp
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  bankapp:

volumes:
    bankapp-volume:
