micronaut.application.name=bankapp
# MySQL Database configuration
datasources.default.url=jdbc:mysql://localhost:3306/bankappdb?useSSL=false&serverTimezone=UTC
datasources.default.username=root
datasources.default.password=Test@123
datasources.default.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate configuration
jpa.default.properties.hibernate.hbm2ddl.auto=update
jpa.default.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
jpa.default.properties.hibernate.show_sql=true
