apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-config
  namespace: bankapp-namespace
data:
  POSTGRES_DB: BankDB
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-svc.bankapp-namespace.svc.cluster.local:5432/BankDB
  SPRING_DATASOURCE_USERNAME: postgres
