apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-config
  namespace: bankapp-namespace
data:
  QUARKUS_MONGODB_DATABASE: BankDB
  QUARKUS_MONGODB_CONNECTION_STRING: mongodb://mongodb-svc.bankapp-namespace.svc.cluster.local:27017
