apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-config
  namespace: bankapp-namespace
data:
  MARIADB_DATABASE: BankDB
  SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb-svc.bankapp-namespace.svc.cluster.local:3306/BankDB?useSSL=false&serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: root
