# namespace
namespace: bankapp-namespace

# name of configmap and database name.
configmap:
  name: bankapp-config
  data:
      MONGO_INITDB_DATABASE: BankDB

## name, label and storage size for database
db_statefulset:
  name: mongodb
  storage: 5Gi

## name and label of app deployment
app_deployment:
  name: bankapp
  cpu_req: 80m
  cpu_limit: 800m
  mem_req: 150Mi
  mem_limit: 700Mi

## image repository and tag of app and db.
image:
  app: trainwithshubham/springboot-bankapp:latest
  db: mongo:7.0

# NodePort svc for bankapp
bankapp_svc:
    port: 8080
    targetPort: 8080
    nodePort: 30080


# headless svc configuration for db
mongodb_svc:
    port: 27017
    targetPort: 27017

# HPA minimun and maximum pods and average cpu utilization
hpa:
    min_replica: 1
    max_replica: 5
    cpu_utilizatoion: 40
