micronaut:
  application:
    name: micronaut-bankapp
  server:
    port: 8080

datasources:
  default:
    url: ${DATASOURCES_DEFAULT_URL:`jdbc:mysql://localhost:3306/BankDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCES_DEFAULT_USERNAME:root}
    password: ${DATASOURCES_DEFAULT_PASSWORD:Test@123}
    dialect: MYSQL

endpoints:
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

logger:
  levels:
    com.example.bankapp: DEBUG
    io.micronaut: INFO
