micronaut:
  application:
    name: micronaut-bankapp
  server:
    port: 8080
  security:
    enabled: true
    session:
      enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true

datasources:
  default:
    url: jdbc:mysql://localhost:3306/bankappdb?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Test@123
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

endpoints:
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

logger:
  levels:
    com.example.bankapp: DEBUG
    io.micronaut: INFO
